### ISSUE TITLE
Enable entries in German

### ISSUE THREAD

**Issue by GoogleCodeExporter** [De7vID/klingon-assistant#11]
```
Enable entries to have German definitions, and if possible, German notes.  Use 
the definitions from "Der Lieven".
```

Original issue reported on code.google.com by `De.vID.jonpIn` on 26 Dec 2012 at 6:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `De.vID.jonpIn` on 26 Dec 2012 at 6:36
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `De.vID.jonpIn` on 26 Dec 2012 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
*ping*
```

Original comment by `De.vID.jonpIn` on 15 Mar 2013 at 6:01

**Comment by De7vID** [comment]
Labeling as "help wanted" since this is basically blocked on the lack of volunteers.
