### ISSUE TITLE
Bug? Unrecognized manifest key "arc_metadata"

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant#128]
When I try to load boQwI' into Chrome (installed ARC Welder before), I always get this warning:

Unrecognized manifest key 'arc_metadata'.

I've seen postings in google that say this is a non-issue and only because of some ARChon specific entries.

Nevertheless, maybe it should be mentioned on the page that explains how to install boQwI' - starting the app takes a long time (I guess, it didn't do anything yet for me), so this warning will likely be seen as a possible reason.

**Comment by De7vID** [comment]
That warning should be safe to ignore.

What operating system and version of Chrome are you using?

**Comment by Cyberman-tM** [comment]
As written in my mail, it works now - the warning is indeed a non-issue, so it can be closed.

The real problem apparently was that the folder where I saved boQwI' was only (write)accessible with admin rights.
