### ISSUE TITLE
Minor typo in mem-18-v.xml , "vul" -> unconcious missing an s: unconscious

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant#194]
Title says all. Not sure how I could fix that myself, I think I would have to clone the project first?

**Comment by LievenLitaer** [comment]
typo has been cleared already. Issue can be closed. I would close it, but don't find the button to do so. :-/

**Comment by Cyberman-tM** [comment]
I can close it, as I opened it.
