### ISSUE TITLE
Suggestion: if backspace is held, delete entire line at once, instead of letter for letter.

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant#209]
Many apps use this, and it's quite convenient, saving time and/or needless tapping.
Although maybe it's already in and doesn't work on my phone?

**Comment by LievenLitaer** [comment]
On my phone, the held backspace button does indeed delete letter by letter, but it's so quick that the line is gone in less than a half second. It goes like "zzzzzip".

**Comment by De7vID** [comment]
This behaviour is a property of the input method, not of the app.
