### ISSUE TITLE
Suggestion: allow edit of (mistyped) input after it was submitted.

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant#253]
Quite often I mistype when I look something up - boQwI' tells me the word doesn't exist, and I have to retype it.
Since I loathe typing on my cell phone, I'd rather have a way to correct my typo instead of writing it again.

Is it possible to make the error message clickable and return the word to the input field?

**Comment by De7vID** [comment]
Will be fixed in next release.
