### ISSUE TITLE
add more song lyrics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [De7vID/klingon-assistant#36]
```
The request is to include lyrics for more Klingon songs.
```

Original issue reported on code.google.com by `De.vID.jonpIn` on 16 Jan 2013 at 8:00

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Added more lyrics in revision 8bedb1d1c941 and revision 0c37ce3ce398. Also 
added Hamlet's {taH pagh taHbe'} soliloquy (not a song, but requested) in 
revision 5781636c61a7.
```

Original comment by `De.vID.jonpIn` on 12 Sep 2013 at 10:38

**Comment by De7vID** [comment]
This request has been made obsolete by qurgh's tlhIngan bommey app: https://play.google.com/store/apps/details?id=org.kag.tlhinganbommey
