### ISSUE TITLE
point to google book store only from one place

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#390]
Many page have them, some do not: A link to the Google download store for KGT and TKD. 
My suggestion would be that any of those lead to a page inside boQwI', with a short description about the book, and from there a link to the Google Play store.

The reason for this idea is that it is not visible that the link leads out of the app, and depending on the phone settings or speed it takes several seconds to abort or go back to he app. when the users stays in the app, he can just hit the back button.

(This actually also applies to other things like youtube videos and )

(PS: while testing around this feature, it seems like I accidentally purchased the book, or only a preview? THIS may also not happen to a user of boQwI'. and by the way, I cannot zoom in to read, but that_'s not boQwI's problem.)

**Comment by De7vID** [comment]
The links exist when they point to something specific inside the book (a specific section or page). It can't work if they all come from a single page.

It shouldn't take several seconds to open the link. For me, it's nearly instantaneous.

**Comment by LievenLitaer** [comment]
Does each of those links lead to the specific page at the Google store?
My intention was for instance a link labeled as "KGT, p. 57" which leads to a page "KGT", with a short description. Then, on that page, there is a link to the Google book store.

And you're right, it's mostly instantaneous.

**Comment by De7vID** [comment]
Each link goes to the specific location in the book which is named in the link, so if it says "TKD 4.2.2", clicking on it goes directly to TKD 4.2.2. Having an intermediate page for this won't work.

**Comment by LievenLitaer** [comment]
Then I must restate my issue: The link does not work for me. I always arrive at the first page of the book.
Is it possible that this only works for you because you have bought the book?

**Comment by De7vID** [comment]
Yes, that's the expected behaviour.

If the user has purchased the book: it goes directly to the section.

If the user has not purchased the book: it shows a preview of the book.

Everything appears to be working exactly as expected.

**Comment by LievenLitaer** [comment]
Okay. Then we can leave as is. One just needs to know that, and to me it seemed like it's not working.
