### ISSUE TITLE
add option: search field non case-sensitive

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#395]
Someone asked to add the option for making the search field not case sensitve. This avoids using caps all the time, but still being able to write correctly. Parallel to [xifan hol] one could call it [tlhingan hol] search method.

**Comment by De7vID** [comment]
This is a weird request. How is this better than xifan hol?

**Comment by LievenLitaer** [comment]
It's maybe better for those people who are comfortable with typing {gh} and {tlh} all the time, but are annoyed by typing capital letters. For me, it's also a bit strange to think of "pef" when typing {peng}. My brain reads "pef" as "PEF" and the connectiong to peng gets troubled.
Using lower case does not change this though, because {bIt} and {bit} both sound the same, {Duj} and {duj} are also still "duj", but the difference between {tlhIngan} and {xifan} is very big.

**Comment by De7vID** [comment]
I tried this and it's terrible. Searching for  {qeq} returns {qeQ}. The distinction between {q} and {Q} is too important to ignore.

**Comment by De7vID** [comment]
Also, you don't have to type "pef". You can still type "peng".
