### ISSUE TITLE
Add Discovery font and make that an option

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#397]
Just an idea; not important - just for fun. 
That would look really cool. I can provide the file if you like.

**Comment by De7vID** [comment]
Sure, send me the font file.

btw if you can edit fonts, you can also fix issue #84 by editing the missing glyphs into the font file.

**Comment by LievenLitaer** [comment]
I can try. But is issue #84 still a problem?
And if I would add those glyphs, which ones are they, and were do you need them added?

**Comment by De7vID** [comment]
Nobody has ever told me issue #84 was a problem except for you. :-) If it's no longer a problem for you, then AFAIK it isn't a problem.

**Comment by LievenLitaer** [comment]
Tell me if that works please.
[Discovery-pIqaD.zip](https://github.com/De7vID/klingon-assistant/files/1414066/Discovery-pIqaD.zip)

**Comment by De7vID** [comment]
Nope.

![DSC font doesn't work](https://user-images.githubusercontent.com/11312380/31993324-1599617a-b97d-11e7-9cec-37fe6ef33ba8.png)

**Comment by LievenLitaer** [comment]
Oh, I see it uses unicode. Just give me a second to fix this.

**Comment by LievenLitaer** [comment]
This one should work now, since I used your file as a basis.
[Discovery pIqaD Unicode.zip](https://github.com/De7vID/klingon-assistant/files/1414327/Discovery.pIqaD.Unicode.zip)

**Comment by De7vID** [comment]
This is in the latest beta.
