### ISSUE TITLE
Ignore hyphens in search results

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#398]
When I search for a suffix _without_ typing the hyphen, it will be shown at the end of a list, probably because of alphabetical order? My wish would be to have it listed on top, see this example, searching for {qa'}, how it should be:

qa' - replace
qa' - ghost
-qa' - suffix resume
qa' wIje'meH ...
qa'meH vIttlhegh ...

**Comment by De7vID** [comment]
This is deliberate. The suffixes are at the end to prevent beginners from looking up "my" and "friend" and ending up with {wIj jup}.

The point is that suffixes are ordered at the end to indicate they're "special".

Also, how often does someone look up a bare suffix?

**Comment by LievenLitaer** [comment]
Actually, I do it all the time: "Was -qa' type 2 or 3?", "Are there any examples for -qoq?", "How do I use -logh corectly?"
I'm not only using boQwI' as a pure dictionary; it has lots of useful other information. I know the answers to the above questions, but to be sure I like look it up.

**Comment by De7vID** [comment]
If you're searching for a suffix, why wouldn't you just type {-qa'}? {boQwI'}'s behaviour here is by design, so that regular words and suffixes aren't mixed together.

**Comment by LievenLitaer** [comment]
Because I'm lazy :-) typing the hyphen needs two clicks, and that's just annoying. But I can live with it.
