### ISSUE TITLE
Lock bottom nav buttons to bottom of screen

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#411]
Currently, the previous-random-next row of buttons is at the bottom of longer entries. This means that the buttons are not on the same location on the screen for all entries, since the user has to scroll to see them if the entry is longer than the screen.

The request is to fix their screen location.

**Comment by De7vID** [comment]
The buttons should hide themselves when the content is scrolled, as described in the [material design guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior).

However, it seems like there isn't [yet](https://stackoverflow.com/questions/42631542/show-hide-bottomnavigationview-on-scroll-in-coordinatorlayout-with-appbarlayout) built-in code to do this.

**Comment by De7vID** [comment]
Another consideration is how this will interact with the tab dots for navigation.

**Comment by LievenLitaer** [comment]
My suggestion (or preference) is to stick the p-r-n buttons to the bottom, and display the tab dots on top of them, as described in the guidelines as "snackbars".
I wouldn't like the bar to disappear when scrolling, because I would need to scroll back to top to get them back.

**Comment by De7vID** [comment]
Fine, done.
