### ISSUE TITLE
Sync database with KWOTD database

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#415]
{boQwI'} fails to retrieve KWOTD when it has an entry missing in {boQwI'}.

**Comment by De7vID** [comment]
Example: {tlhIngan 'IH qaD}

We could just accept the definition coming from the server, but it's only in English. Also, we'd have to parse the query, which results in {tlhIngan:n}, {'IH:v}, {qaD:n} or {qaD:v}. We know the entire thing is a noun, so we can eliminate {qaD:v}, but that requires additional logic.

**Comment by LievenLitaer** [comment]
Just treat it as a search result, so you don't need to program any thing new.

**Comment by De7vID** [comment]
Okay, done. The downside of this is that for some entries, the definition won't show in German in the notification, and the actual result will be multiple entries (which may include spurious things like the {qaD:v} in the example above).
