### ISSUE TITLE
Support inclusion in F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [De7vID/klingon-assistant#448]
Please support the inclusion of this app in the F-Droid app store, see https://gitlab.com/fdroid/rfp/issues/503

PS Please fix the Google Play download badge and URLs in README.md. (When this app is in F-Droid, I will make a PR for a download badge for that repo.)

PPS If you can translate "GET IT ON" into Klingon (Latin and pIqaD), I can create a download badge in Klingon for F-Droid at https://gitlab.com/fdroid/artwork/tree/master/badge

**Comment by PanderMusubi** [comment]
and there is a small typo in one of the READMEs: `../asserts/qawHaq.db` which should be `../assets/qawHaq.db`

**Comment by Poussinou** [comment]
Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

**Comment by PanderMusubi** [comment]
@De7vID, here friendly reminder to add a tagged release so that this app can be included in the F-Droid app store. Thanks.

**Comment by De7vID** [comment]
It doesn't make sense to create tagged releases for this repo, which groups together different projects each of which has its own version numbers.

**Comment by PanderMusubi** [comment]
Could you perhaps find a way around this, please? Perhaps create a tagged release with in the comment which underling versions are included? Otherwise, this app can not be build for F-Droid.

**Comment by De7vID** [comment]
Aren't you pointing to the wrong repo, though? This repo can't be built into an app.

I think you want the specific apps to be tagged, like so:
https://github.com/De7vID/klingon-assistant-android/releases/tag/v2018.11.20a
https://github.com/De7vID/klingon-assistant-tts-android/releases/tag/v2018.12.06

**Comment by PanderMusubi** [comment]
You are right, that is the one! Thanks.

**Comment by De7vID** [comment]
FYI, there's a new release:
https://github.com/De7vID/klingon-assistant-android/releases/tag/v2019.07.23a

**Comment by De7vID** [comment]
I'm told that the F-Droid version doesn't work because the database isn't packaged with the app (it's empty). How does F-Droid handle git submodules? I suspect (if the report is correct) that it isn't pulling in the data submodule when compiling the Android app.
