### ISSUE TITLE
Word database access

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [De7vID/klingon-assistant#468]
From where is the database of Klingon words being taken? I would like to use it too for a web interface.

**Comment by De7vID** [comment]
The database is [here](https://github.com/De7vID/klingon-assistant-data).

btw if you're just thinking of implementing a Klingon dictionary or parser online, one already exists at [https://hol.kag.org/](https://hol.kag.org/).

**Comment by De7vID** [comment]
If you have no further questions, I'm closing this issue. Feel free to reopen if you want to follow up or need additional help with something.
