### ISSUE TITLE
Unrecognized manifest key 'arc_metadata' - Clarius app

### ISSUE THREAD

**Issue by wnesbit** [De7vID/klingon-assistant#479]
I've successfully loaded ARChon Custom Runtime 1.2 - x86_64 to google chrome Version 80.0.3987.122 (Official Build) (64-bit) 

I've installed nodejs 

system:  mac IOS - High Sierra. 

I'm trying to convert and run an app:
Clarius - downloaded here:

[https://apkpure.com/clarius-ultrasound-app/me.clarius.clarius](url)

I've tried converting the app in terminal with these chromeos-apk commands:

chromeos-apk /Downloads/Clarius\ Ultrasound\ App_v6.1.5_apkpure.com.apk --tablet

and

chromeos-apk /Downloads/Clarius\ Ultrasound\ App_v6.1.5_apkpure.com.apk

This app is made to run on android, iphone or ipad, but not on Mac/PC. 

These are the errors I'm getting after conversion.    
Any help!???????

![Screen Shot 2020-03-01 at 12 12 17 AM](https://user-images.githubusercontent.com/61644665/75620683-64cf3080-5b51-11ea-9c77-d495c96230a4.png)

![Screen Shot 2020-03-01 at 12 12 17 AM](https://user-images.githubusercontent.com/61644665/75620687-71ec1f80-5b51-11ea-802d-852858722e54.png)

**Comment by De7vID** [comment]
Did you mean to file this issue in another repository? I don't see what it has to do with this one.
