### ISSUE TITLE
generate an Anki deck from the database

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#482]
The feature request is to add functionality to generate an Anki deck from the database. 

Suggestion is to use the [genanki](https://github.com/kerrickstaley/genanki) project.

If a Klingon entry and part of speech are unique, then the front would have the Klingon and part of speech, and the back would have the English (or German or whatever) definition, and a reverse card should also be generated.

If there are homophones which are the same part of speech, then one card should be generated with Klingon in the front and all English (or whatever) definitions in the back, each separately numbered. Then one card each should be generated for each English (or whatever) definition, with the Klingon in the back.

**Comment by De7vID** [comment]
The functionality has been written, but the deck hasn't been shared to Ankiweb.

**Comment by De7vID** [comment]
Additional feature request: tag the cards by source. In particular, the request is to tag the new vocabulary from the more recent **qep'a'** and **qepHom'a'** because there have been so many new words recently it's hard to keep up.

**Comment by De7vID** [comment]
The cards are tagged by source now.

**Comment by De7vID** [comment]
Shared deck available at https://ankiweb.net/shared/info/1723013188 thanks to Thiago Matos.

**Comment by De7vID** [comment]
German and Portuguese decks also made available. I think that satisfies everyone's requests who've asked me about it, so I'm closing the issue. If anyone else has any further requests, feel free to open another issue or reopen this one.

**Comment by thiagocmatos** [comment]
The shared Deck was updated. It is available at https://ankiweb.net/shared/info/1406312503
