### ISSUE TITLE
add "Klingon Word of the Day" notification

### ISSUE THREAD

**Issue by GoogleCodeExporter** [De7vID/klingon-assistant#64]
```
qurgh runs a "Klingon Word of the Day" that is posted to various forums (KLI 
mailing list, Facebook "Learn Klingon" group). The request is to have {boQwI'} 
display this as an Android notification every day.
```

Original issue reported on code.google.com by `De.vID.jonpIn` on 5 Dec 2014 at 8:04

**Comment by GoogleCodeExporter** [comment]
```
The difficulty would be to keep this in sync with qurgh's list, since it's 
generated randomly (is it?).
```

Original comment by `De.vID.jonpIn` on 5 Dec 2014 at 8:04

**Comment by qurgh** [comment]
Yes, it's random, but it can be scraped from the web at:

http://hol.kag.org/kwotd.rss
http://hol.kag.org/kwotd.xml

The second one was designed for Windows live tiles. It's update at 10am EST each day.

**Comment by De7vID** [comment]
Some considerations:
- displaying the text verbatim will support only English (not German, which {boQwI'} now fully supports)
- maybe some kind of extraction and matching can be done to the {boQwI'} entry, but some entries won't be exact matches

**Comment by De7vID** [comment]
KWOTD can also be fetched as JSON:
http://hol.kag.org/alexa.php?KWOTD=1

**Comment by De7vID** [comment]
@qurgh - How stable are these URLs? Which one is preferable to use?

**Comment by qurgh** [comment]
The Alexa one is probably the most useful.

**Comment by De7vID** [comment]
This feature is in the latest stable release.
