### ISSUE TITLE
con.mp3 can't be saved in Windows

### ISSUE THREAD

**Issue by NoahTheDuke** [De7vID/klingon-assistant#78]
con.mp3 is an illegal filename in Windows. Files, regardless of extension, [cannot be named con](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions).

So I can't clone the repository. I know it'd be a hassle, but is there some way this single file could be renamed?

**Comment by De7vID** [comment]
What happens if you try to clone the repo? And out of curiosity, what happens in Windows when, e.g., you unzip a file which contains a file named "con.mp3"?

**Comment by De7vID** [comment]
I've renamed the file (actually, all of the audio files). Let me know if you encounter any other problems.
