### ISSUE TITLE
add hyphen to pIqaD

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#84]
When analysing words in pIqaD, hyphenated words have a strange symbol used for htte hyphen, e.g. in {-Daq}. Replace this by a true dash, or use the zero symbol (which also looks like a dash).

**Comment by De7vID** [comment]
I tried it with a hyphen, it looks wrong next to the pIqaD letters. I'm also not going to use "0" since that obviously means something else. 

What's wrong with the current symbol? It follows the convention used on the SkyBox cards, though I turned it sideways to indicate the joining direction.

**Comment by LievenLitaer** [comment]
Maybe it's just because I don't know that symbol. On which SBcard has it been used? It looks so un-pIqaD. Or maybe you see something else than I do? Verify my screenshot.
<b>EDIT:</b> I just checked the SB Cards, they don't even use "traditional" pIqaD. Did you intend to use the triangle instead? That would mae sense.
![hyphen](https://cloud.githubusercontent.com/assets/11874228/7083726/747ff478-df65-11e4-8ea2-ecf30696fc68.png)

**Comment by De7vID** [comment]
They are supposed to look like triangles, and they always point towards the verb:
![arrows](https://cloud.githubusercontent.com/assets/11312380/7090023/68542558-dfa0-11e4-8845-48387013e8a8.png)

Maybe it wasn't the SkyBox cards, but there was somewhere where triangles were used as punctuation.

When I added support for {pIqaD}, I expected that they wouldn't display perfectly on every device. There's no way for me to guarantee that.

**Comment by LievenLitaer** [comment]
a) Yes, Skybox did use triangles for punctuation, and I really like your use of left and right arrows. It looks nice and makes sense.
b) to display pIqaD, I suppose you have included some font file, right? So why does it not show the correct symbol when it's told to? especially only in this case?

**Comment by De7vID** [comment]
Because the triangles are not part of the pIqaD font. Rather, they're Unicode characters U+25C3 and U+25B9. Your phone can't display them because someone has decided not to include those characters in your system font (probably because they think no one will use them and they want to save space, which some phone manufacturers do).

**Comment by De7vID** [comment]
Can I close this issue or do you think the triangles (◃, ▹) should be replaced with, e.g., (<, >)? I think every other character looks out of place.

**Comment by LievenLitaer** [comment]
I don't know how man people have problems with this triangles. I'm sure I'm not the only one, although I don't know how man people use pIqaD... Using < and > is of course easiest way to solve it.

**Comment by De7vID** [comment]
@qurgh - Is it possible to include some punctuation triangles in the pIqaD font?

**Comment by De7vID** [comment]
@LievenLitaer - Is this still a problem for you?

**Comment by LievenLitaer** [comment]
I have a new phone now (Android 6), and the triangles you showed above are working fine.

**Comment by qurgh** [comment]
There already are triangles in the pIqaD font: 
