### ISSUE TITLE
prefix chart is squashed in portrait mode

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#85]
This can also happen in landscape mode in devices with smaller screens.

**Comment by Cyberman-tM** [comment]
At least on one device (LG K500Y, Android 6.0.1) the prefix chart is too big for portrait mode and doesn't allow scrolling - i.e. anything beyond the plural "you" is invisible with no indication that there is more.

[edit]I'm not sure where to find the version of boQwI' ? It's the current version anyhow, databse version 2017.05.29a .

**Comment by De7vID** [comment]
This is hard to fix, because swiping right opens the menu, so once you've scrolled the chart it's impossible to scroll back.

**Comment by De7vID** [comment]
It's now possible to scroll the chart back to the left even if it's scrolled to the far right by first swiping left, then (without letting go) swipe right.
